build.cmd, sample/FunctionApp/FunctionApp/FunctionApp.csproj, sample/nuget.config
- Adding tooling package to sample project
- adding nuget.config to pull in the references
- Fixing the build.cmd to build and publish the sample project.
@ahmelsayed @soninaren
=> Fixing the sample to have tooling package & fixing build.cmd

src/Microsoft.NET.Sdk.Functions/Targets/Sdk/Sdk.props, src/Microsoft.NET.Sdk.Functions/Targets/Sdk/Sdk.targets, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.targets
@ahmelsayed 
Fix for 
https://github.com/Azure/azure-functions-vs-build-sdk/issues/30
=> Changing MsBuildSDKsPath to Import Sdk

ProjectTemplate/Microsoft.AzureFunctions.ProjectTemplates/content/FunctionApp/Company.FunctionApp.csproj, sample/FunctionApp/FunctionApp/FunctionApp.csproj, src/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.targets, src/Microsoft.NET.Sdk.Functions/Tasks/BuildFunctions.cs
@vijayrkn @ahmelsayed 
Fixes #3
=> Fix issue #3

src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.props, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Publish.props, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Publish.targets, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.References.targets, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.props, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.targets
@soninaren @ahmelsayed 
This target needs to be updated with the correct runtime reference versions - Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.References.targets
=> Adding package references to the targets

src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Publish.targets
To support referencing a function project from another function project.
=> Fixing the copying of application dll

build.cmd, sample/FunctionApp/FunctionApp.sln, sample/FunctionApp/FunctionApp/FunctionApp.csproj, sample/FunctionApp/FunctionsRefClassicClassLib/Class1.cs, sample/FunctionApp/FunctionsRefClassicClassLib/FunctionsRefClassicClassLib.csproj, sample/FunctionApp/FunctionsRefClassicClassLib/Properties/AssemblyInfo.cs, sample/FunctionApp/FunctionsRefSdkClassLib/Class1.cs, sample/FunctionApp/FunctionsRefSdkClassLib/FunctionsRefSdkClassLib.csproj, sample/FunctionApp/UnitTestProject1/Properties/AssemblyInfo.cs, sample/FunctionApp/UnitTestProject1/UnitTest1.cs, sample/FunctionApp/UnitTestProject1/UnitTestProject1.csproj, sample/FunctionApp/UnitTestProject1/packages.config, sample/FunctionApp/UnitTestProject2/UnitTest1.cs, sample/FunctionApp/UnitTestProject2/UnitTestProject2.csproj, sample/FunctionApp/XUnitTestProject1/UnitTest1.cs, sample/FunctionApp/XUnitTestProject1/XUnitTestProject1.csproj, sample/NuGet/NuGet.csproj, sample/NuGet/Program.cs, src/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets
@ahmelsayed  
/cc @lindydonna 
Fix for https://github.com/Azure/azure-functions-vs-build-sdk/issues/94
=> Fix the p2p references from default unit test project

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Publish.props
https://github.com/Azure/azure-functions-vs-build-sdk/issues/113
=> Fixing the casing for Sdk.props

sample/FunctionApp/FunctionApp/FunctionApp.csproj
@ahmelsayed - Can you please update the sample version also when the main package version is updated.
=> Update the sample version also to 1.0.4

build.cmd, sample/FunctionAppNETStandard/FunctionAppNETStandard.sln, sample/FunctionAppNETStandard/UnitTestNETFramework/DefaultHttpRequest.cs, sample/FunctionAppNETStandard/UnitTestNETFramework/UnitTestNETFramework.cs, sample/FunctionAppNETStandard/UnitTestNETFramework/UnitTestNETFramework.csproj, sample/FunctionAppNETStandard/UnitTestProject2/DefaultHttpRequest.cs, sample/FunctionAppNETStandard/XUnitTestProject1/DefaultHttpRequest.cs, sample/FunctionAppNETStandard/XUnitTestProject1/UnitTest1.cs
Adding a unit test project that targets net461 to test the netstandard function app
=> Adding NetStandard tests

src/Microsoft.NET.Sdk.Functions.Generator/BuildArtifactsLog.cs, src/Microsoft.NET.Sdk.Functions.Generator/ConsoleLogger.cs, src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs, src/Microsoft.NET.Sdk.Functions.Generator/ILogger.cs, src/Microsoft.NET.Sdk.Functions.Generator/MethodInfoExtensions.cs, src/Microsoft.NET.Sdk.Functions.Generator/Microsoft.NET.Sdk.Functions.Generator.csproj, src/Microsoft.NET.Sdk.Functions.Generator/Program.cs, test/Microsoft.NET.Sdk.Functions.Generator.Tests/FunctionJsonConverterTests.cs, test/Microsoft.NET.Sdk.Functions.Generator.Tests/Microsoft.NET.Sdk.Functions.Generator.Tests.csproj, test/Microsoft.NET.Sdk.Functions.Generator.Tests/RecorderLogger.cs, test/Microsoft.NET.Sdk.Functions.Generator.Tests/packages.config
Methods with NoAutomaticTriggerAttribute will be exported as "manualTrigger" functions, as documented on https://github.com/Azure/azure-webjobs-sdk-script/wiki/function.json
Fixes #15
=> Add support for [NoAutomaticTrigger]

src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs
Only methods with a FunctionNameAttribute are relevant for generation.
The generator checks all public types. During the checks (if the necessary attributes are present) it loads dependent assemblies (indirectly - to get the parameters of the methods). During this step an error can occur, because the dependent assembly cannot be loaded.
To avoid such errors, the check for the presence of a FunctionNameAttribute is done before the other checks.
Because only methods with a FunctionNameAttribute are relevant for the generation of function.json, the compile error can be avoided by only taking methods with a FunctionNameAttribute into account.
Should fix the compile errors (at least as a workaround) for #150 #139 #115
=> Add check if method has FunctionNameAttribute before other checks

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj
=> Add reference to Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator

src/Microsoft.NET.Sdk.Functions.Generator/AttributeExtensions.cs, src/Microsoft.NET.Sdk.Functions.Generator/CustomAttributeDataExtensions.cs, src/Microsoft.NET.Sdk.Functions.Generator/MethodInfoExtensions.cs
This prevents System.IO.FileNotFoundExceptions when building a .NET Framework application using dotnet build.
=> Retrieving custom attributes through reflection-only load.

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj, sample/FunctionAppNETFramework/FunctionAppNETFramework/FunctionAppNETFramework.csproj, sample/FunctionAppNETFxNETStandard/FunctionAppNETFramework/FunctionAppNETFramework.csproj
=> Adding System.ValueTuple along with the generator

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj
=> Updating the NuGet dependency for extension packages

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj
=> Add repository URL

build.fsx
=> Fixing the build path in GenerateZipToSign task and WaitForSigning task in build.fsx

build.fsx
Now signing the nuget package after the build is complete. Verified it all works in Appveyor.
@ahmelsayed -- I'm no good with F#/Fake (yet?), so let me know if any of this looks like it can be cleaned up.
=> adding nupkg signing

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.targets
Fixes https://github.com/Azure/azure-functions-host/issues/4133.
=> import the ExtensionsMetadataGenerator targets last

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Publish.targets
=> Disable Publish as part of pack if property is set

src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs
See https://github.com/Azure/azure-functions-core-tools/pull/1174 and https://github.com/Azure/azure-functions-core-tools/issues/1133
=> remove warning for kafka extension

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/ExtensionsMetadataGeneratorVersion.props
note -- still waiting for the 1.1.0 release of that package, but getting this ready.
=> Updating ExtensionsMetadataGenerator version

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj, src/Microsoft.NET.Sdk.Functions.MSBuild/Http/HttpClientHelpers.cs, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Publish.ZipDeploy.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Version.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/ZipDeployTask.cs, test/Microsoft.NET.Sdk.Functions.MSBuild.Tests/ZipDeployerTaskTests.cs
=> Set User-Agent header to ZipDeploy task

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj
=> Relaxing Json.NET reference for 2.x

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj
=> Bumped v1 version dependencies to resolve conflict

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.targets
=> base deps file copy on AssemblyName, not ProjectName

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/ExtensionsMetadataGeneratorVersion.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Version.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.props
=> adding _IsFunctionsSdkBuild to props file; bumping versions (v3)

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/ExtensionsMetadataGeneratorVersion.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Version.props
=> copy all bin/pdb files to /bin during build

build.fsx
=> running unit tests during ci

Directory.Build.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Publish.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Version.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/GenerateFunctions.cs
=> Fixing the task assembly load issue

Directory.Build.props, FunctionsSdk.sln, appveyor.cmd, build.fsx, pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj, src/Microsoft.NET.Sdk.Functions.Generator/Microsoft.NET.Sdk.Functions.Generator.csproj, src/Microsoft.NET.Sdk.Functions.MSBuild/Microsoft.NET.Sdk.Functions.MSBuild.csproj, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Publish.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/GenerateFunctions.cs, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/FunctionsSdkTests.cs, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/Microsoft.NET.Sdk.Functions.EndToEnd.Tests.csproj, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/ProcessWrapper.cs, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/Resources/FunctionAppWithHttpTrigger/FunctionAppWithHttpTrigger.csproj, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/Resources/FunctionAppWithHttpTrigger/HttpFunction.cs, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/Resources/FunctionAppWithHttpTrigger/host.json, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/Resources/FunctionAppWithHttpTrigger/local.settings.json, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/Resources/FunctionsSdk/FunctionsSdk.csproj, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/Resources/FunctionsSdkWithSQLClient/FunctionsSdkWithSQlClient.csproj, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/TestInitialize.cs, test/Microsoft.NET.Sdk.Functions.Generator.Tests/Microsoft.NET.Sdk.Functions.Generator.Tests.csproj, test/Microsoft.NET.Sdk.Functions.MSBuild.Tests/Microsoft.NET.Sdk.Functions.MSBuild.Tests.csproj
- Copying the runtimes folder also as part of post build step
- Removing the target override of pack with publish
=> Copying the runtime folder as part of post  build step

src/Microsoft.NET.Sdk.Functions.MSBuild/Properties/Resources.Designer.cs, src/Microsoft.NET.Sdk.Functions.MSBuild/Properties/Resources.resx, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/DeployStatus.cs, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/Http/DefaultHttpClient.cs, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/Http/HttpClientHelpers.cs, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/Http/IHttpClient.cs, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/ZipDeployTask.cs, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/ZipDeploymentStatus.cs, test/Microsoft.NET.Sdk.Functions.MSBuild.Tests/ZipDeployerTaskTests.cs, test/Microsoft.NET.Sdk.Functions.MSBuild.Tests/ZipDeploymentStatusTests.cs
Fixes https://github.com/Azure/azure-functions-vs-build-sdk/issues/413
Fixes https://github.com/Azure/azure-functions-vs-build-sdk/issues/441
=> Changing the ZipDeploy call to async

src/Microsoft.NET.Sdk.Functions.Generator/Program.cs, test/Microsoft.NET.Sdk.Functions.Generator.Tests/ArgumentsTests.cs
v3 version of #466 (fix for #458)
=> fixing issue with args passed to Functions.Generator [v3]

src/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/Resources/v1/FunctionAppNETStandard/UnitTestNETFramework/UnitTestNETFramework.csproj
=> updating package refrences

FunctionsSdkE2ETests/FunctionsSdkE2ETests.sln, FunctionsSdkE2ETests/FunctionsSdkE2ETests/E2ETests.cs, FunctionsSdkE2ETests/PreservedDependencies.sln, FunctionsSdkE2ETests/PreservedDependencies/Function1.cs, FunctionsSdkE2ETests/PreservedDependencies/PreservedDependencies.csproj, FunctionsSdkE2ETests/PreservedDependencies/host.json, FunctionsSdkE2ETests/PreservedDependencies/local.settings.json, FunctionsSdkE2ETests/SdkVersion.props
Related to https://github.com/Azure/azure-functions-host/pull/6849
Based on issue https://github.com/Azure/azure-functions-host/issues/5894
=> Added tests for FunctionsPreservedDependencies functionality.

README.md
Port of Azure/azure-functions-vs-build-sdk/pull/535.
=> Updated pipeline badges.

common.props, src/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj
=> Update package dependencies

FunctionsSdkE2ETests/nuget.config, eng/ci/code-mirror.yml, eng/ci/official-build.yml, eng/ci/public-build.yml, eng/ci/templates/jobs/build-and-test.yml, eng/ci/templates/variables/build.yml, nuget.config, paket.dependencies
Added 1ES pipeline files in release branch
=> [1ES] [release4] Added 1ES pipeline files

eng/ci/official-build.yml, eng/ci/public-build.yml
Enables CodeQL on public builds and some other CI settings.
=> Enable codeql on public

common.props
Release prep - main change is [this ](https://github.com/Azure/azure-functions-vs-build-sdk/pull/662/files).
=> Bump package version
