sample/nuget.config
Forward slashes as path separators should work on Windows, but
backslashes don't work on Unix.
=> Work around NuGet path issue

src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.targets
@ahmelsayed @lindydonna 
Work-around to make publishing the content files work. Permanent fix would be to identify the binaries and move them to bin and copy the rest outside.
=> Moving all the publish contents outside bin

ProjectTemplate/nuget.config
https://github.com/Azure/azure-functions-vs-build-sdk/issues/37
@ahmelsayed @soninaren @bzhu94 
This nuget.config is only used by samples. This shouldn't be needed in the project templates.
=> Remove nuget.config inside ProjectTemplates folder

src/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj
Updating the preview version to the latest stable version to fix the warnings during restore.
=> Update the msbuild package versions to latest stable

src/Microsoft.NET.Sdk.Functions/MakeFunction/FunctionJsonSchema.cs, src/Microsoft.NET.Sdk.Functions/MakeFunction/MethodInfoExtensions.cs, src/Microsoft.NET.Sdk.Functions/MakeFunction/ParameterInfoExtensions.cs, src/Microsoft.NET.Sdk.Functions/MakeFunction/TypeInfoExtensions.cs, test/Microsoft.NET.Sdk.Functions.Test/DisableAttributeTests.cs, test/Microsoft.NET.Sdk.Functions.Test/Microsoft.NET.Sdk.Functions.Test.csproj, test/Microsoft.NET.Sdk.Functions.Test/app.config, test/Microsoft.NET.Sdk.Functions.Test/packages.config
Provided solution for the issue described in #69.
The Test project did not compile out of the box, so I had to update some NuGet references there.
Please note my assumption in `MethodInfoExtensions.cs` at line 122. `ScriptHost.IsDisabled(..)` does not actually seem to support the ProviderType (yet?). Based on a discussion in Azure/azure-webjobs-sdk#578 I've assumed the full type name would be in the text field, such as when the settingName does not exist, it would try to see if it could load the Type.
=> Support for DisableAttribute overloads

src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets, src/Microsoft.NET.Sdk.Functions/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Publish.targets
@ahmelsayed @watashiSHUN 
When there are duplicate slashes in the path, msbuild move task is throwing an exception in Kudu but still copies the files.  This PR is to remove the duplicate slashes from the path.
=> Fixing the slashes

test/Microsoft.NET.Sdk.Functions.Generator.Tests/Microsoft.NET.Sdk.Functions.Generator.Tests.csproj, test/Microsoft.NET.Sdk.Functions.Generator.Tests/packages.config
Version 2.3.0-beta4-build3724 that was referenced in Microsoft.NET.Sdk.Functions.Generator.Tests.csproj is not available on nuget.org making it impossible to run tests because NuGet restore would fail.
=> Upgrade to xunit 2.3.1

src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/GenerateFunctions.cs
The output from the generator process is checked and only logged as warning, if the output is not empty.
When a project was built from Visual Studio, the build task logged the process output as warning, even when the output was empty. This resulted in an empty warning in Visual Studio.
Fixes #149
=> Fix empty warning on build

src/Microsoft.NET.Sdk.Functions.Generator/PathUtility.cs
This change fixes the issue posted here: 
https://github.com/Azure/azure-functions-vs-build-sdk/issues/142
Basically using windows specific directory separator caused PathUtility to generate an incorrect relative path to the assembly from the function.json. This incorrect value is set in function.json which does not work.
=> Use platform aware directory separators

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.props
This adds globs to cover host.json and local.settings.json to the build props. A couple people have run in to situations where the entries covering these files have been removed from the csproj file & therefore end up with a "No job functions found" message coming from the CLI (https://developercommunity.visualstudio.com/content/problem/149690/no-job-functions-found-message-with-unchanged-azur.html)
With this change, these entries could be removed from the default project file.
cc @vijayrkn
=> Add updates for host.json and local.settings.json to the build props

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj, sample/FunctionAppNETFramework/FunctionAppNETFramework/FunctionAppNETFramework.csproj, sample/FunctionAppNETFxNETStandard/FunctionAppNETFramework/FunctionAppNETFramework.csproj, src/Microsoft.NET.Sdk.Functions.MSBuild/Properties/AssemblyInfo.cs, src/Microsoft.NET.Sdk.Functions.MSBuild/Properties/Resources.Designer.cs, src/Microsoft.NET.Sdk.Functions.MSBuild/Properties/Resources.resx, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Publish.ZipDeploy.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/ZipDeployTask.cs, test/Microsoft.NET.Sdk.Functions.MSBuild.Tests/Microsoft.NET.Sdk.Functions.MSBuild.Tests.csproj, test/Microsoft.NET.Sdk.Functions.MSBuild.Tests/ZipDeployerTaskTests.cs
This fixes publish for profiles that were created prior to 15.8 Preview 4
=> Fixing ZIP Deploy for profiles that have DeployIisAppPath instead of PublishUrl

pack/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj
Preparing to release 2.3.0 packages, but the current 1.0.23 version of the tools isn't inclusive of this version, causing package installation to fail.
=> Updating package version ranges to be inclusive

nuget.config, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/ExtensionsMetadataGeneratorVersion.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.targets
Fixes https://github.com/Azure/azure-functions-host/issues/4383.
Part of the fix for https://github.com/Azure/azure-functions-vs-build-sdk/issues/277.
In conjunction with https://github.com/Azure/azure-functions-host/pull/4398.
Several pieces here:
- If `NUGET_PACKAGES` is missing a trailing slash, the property `NugetPackageRoot` will also be missing that slash.  We didn't take that into account so our paths weren't resolving to anything in this case. It was tough to diagnose because some things *do* work -- like the auto-generated `nuget.g.props/.targets' files. These take this into consideration and create the correct string depending on what this property has. Ensuring the trailing slash will fix one class of issues.
- If someone were to directly reference `ExtensionsMetadataGenerator` …
=> allowing for a direct reference to ExtensionsMetadataGenerator

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/ExtensionsMetadataGeneratorVersion.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.targets
Fixes https://github.com/Azure/azure-functions-host/issues/4545.
My check for ExtensionsMetadataGenerator was too aggressive and failed in v1 apps if you didn't already happen to have the ExtensionsMetadataGenerator installed in your nuget cache. So:
- Only check on v2 apps (it'll still be useful for debugging build failures).
- Change it to a warning so it doesn't completely blow up.
=> removing check for ExtensionsMetadataGenerator in v1 projects

build.cmd, devbuild.cmd, sample/FunctionAppNETFramework/FunctionAppNETFramework/FunctionAppNETFramework.csproj, sample/FunctionAppNETFramework/FunctionAppNETFramework/RefUser.cs, sample/FunctionAppNETFramework/FunctionsRefSdkClassLib/Class1.cs, sample/FunctionAppNETFramework/FunctionsRefSdkClassLib/FunctionsRefSdkClassLib.csproj, sample/FunctionAppNETFramework/FunctionsRefSdkClassLib/HttpTriggerRefSdkNETFramework.cs, sample/FunctionAppNETFramework/UnitTestProject1/UnitTest1.cs, sample/FunctionAppNETFramework/UnitTestProject2/UnitTest1.cs, sample/FunctionAppNETFramework/XUnitTestProject1/UnitTest1.cs, sample/FunctionAppNETStandard/FunctionAppNETStandard/FunctionAppNETStandard.csproj, sample/FunctionAppNETStandard/FunctionAppNETStandard/RefUser.cs, sample/FunctionAppNETStandard/FunctionsRefNETStandard/Class1.cs, sample/FunctionAppNETStandard/FunctionsRefNETStandard/FunctionsRefNETStandard.csproj, sample/FunctionAppNETStandard/FunctionsRefNETStandard/HttpTriggerRefNETStandard.cs, sample/FunctionAppNETStandard/UnitTestNETFramework/UnitTestNETFramework.cs, sample/FunctionAppNETStandard/UnitTestProject2/UnitTest1.cs, sample/FunctionAppNETStandard/XUnitTestProject1/UnitTest1.cs, src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs, src/Microsoft.NET.Sdk.Functions.Generator/Program.cs, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Build.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/netstandard1.0/Microsoft.NET.Sdk.Functions.Publish.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/GenerateFunctions.cs
* This functionality is off by default; to enable, set the project property
`FunctionsInDependencies` to True.
* Compilers can be too smart, and may strip out unused references. To ensure
that a referenced project's DLL is included in the assembly's dependencies,
make sure the assembly's code explicitly references a member or type from the
referenced project.
=> Generator scans assembly's dependencies for functions. Resolves #274.

src/Microsoft.NET.Sdk.Functions.Generator/Microsoft.NET.Sdk.Functions.Generator.csproj, src/Microsoft.NET.Sdk.Functions.MSBuild/Microsoft.NET.Sdk.Functions.MSBuild.csproj, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Publish.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Version.props
Assemblies under runtimes were not being properly copied to the bin folder (https://github.com/Azure/Azure-Functions/issues/1370). It looks like the way publish files are computed has changed between v2 and v3. 
Here we explicitly set the `ReferenceCopyLocalPaths.DestinationSubDirectory` with bin\: https://github.com/Azure/azure-functions-vs-build-sdk/blob/master/src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.targets#L152
This works for the build, but not for publish.
It looks like this is trying to pick that metadata and apply it to `_ResolvedCopyLocalPublishAssets`: https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L574
But I added a bunch of logging and reviewed it in binlogs and it …
=> fixing publish; changing assemblies to 3.0.0

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Publish.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Version.props
Fixes #333 
This is a port of #354 for the 1.0 release. If .NET Core 3 SDK is installed, the targets used are different and we were missing this step in this case. I tested this with targeting the 2.2 SDK as well and it continued to work (this target won't get hit in that scenario).
=> fixing publish for v2 apps with .NET Core 3 SDK installed

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.targets
If your assembly name didn't match your project name, we'd fail to copy the deps.json file. Thanks to @Ponomareff for catching this here: https://github.com/Azure/Azure-Functions/issues/1370#issuecomment-565086901
=> base deps file copy on AssemblyName, not ProjectName [v3.x]

src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs, src/Microsoft.NET.Sdk.Functions.Generator/Program.cs, src/Microsoft.NET.Sdk.Functions.Generator/TypeUtility.cs
Fix assembly loading when dealing with different versions of libraries
than what the SDK has a dependency on. This should resolve numerous
issues with types not loading in the generator itself. In addition, some
places where you typically would get a rather unhelpfull
`NullReferenceException`, a check for null values have been added,
throwing `InvalidOperationException`s with more helpfull error messages.
Resolves #359
=> Fix assembly loading

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Publish.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Version.props
When fixing #363, I missed the change to the publish targets.
=> basing deps copy (for publish) on AssemblyName [v3.x]

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/ExtensionsMetadataGeneratorVersion.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Version.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.props
Moving this setting explicitly to a props file allows us to take advantage of this in ExtensionsMetadataGenerator. Note that 1.1.7 doesn't exist yet -- that'll be published soon.
=>  adding _IsFunctionsSdkBuild to props file; bumping versions

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/ExtensionsMetadataGeneratorVersion.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Version.props
Part 2 of https://github.com/Azure/azure-functions-host/issues/5963.
One of the issues here was the discrepancy between what we do during a build and what we do during a publish. Previously, during a build, we'd only copy the project pdb and assembly to the /bin folder. During publish, we copy all pdb and dlls. So in the case of this bug, the customers all ran into an issue during publish, but not during build (and the build behavior was wrong).
I've copied this publish logic and moved it to build: https://github.com/Azure/azure-functions-vs-build-sdk/blob/master/src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Publish.targets#L152-L160
=> copy all bin/pdb files to /bin during build

Directory.Build.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Publish.targets, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Version.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/GenerateFunctions.cs
Fix this issue: https://github.com/Azure/azure-functions-vs-build-sdk/issues/199
This should allow the 3 versions of the assemblies to load side by side
=> Fixing the task assembly load issue

src/Microsoft.NET.Sdk.Functions.MSBuild/Tasks/GenerateFunctions.cs
The cherry-pick change from 2.1 caused the path to be changed to netcoreapp2.1 instead of netcoreapp3.0. Fixing.
=> Fixing the path to the task dll

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Build.targets
Functions runtime/core-tools expect the binaries to be present in the bin folder but VS on normal builds creates them in the root folder. The previous implementation was to move these files to the bin folder on generation. 
Issue: 
Since the binary folder is different compared to the other .NET Core projects, some of the features in VS does not work properly. e.g: Find all references, references to types needs re-builds, incremental build does not work etc. 
Fix: 
Remove the logic to move the files. Instead after the files are generated to bin, copy the required binaries to the bin folder for the functions core-tools to function. Since we are not moving the assemblies, all VS functionalities should work as expected. 
Publish Impact: None. Publish should just work. The duplicate content …
=> Fix 'Find All References' and other features in VS caused due to moving files to 'bin' folder

src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs
We plan to release public support for non-Azure Storage backends for Durable Functions. In order for the VS build SDK to fully support this, we need to exclude Durable triggers from the list of triggers requiring `AzureWebJobsStorage`.
Note that we already made the same change for the Functions Core Tools: https://github.com/Azure/azure-functions-core-tools/pull/2409
=> Add Durable triggers to TriggersWithoutStorage

README.md
It looks like we've shifted our build pipelines from AppVeyor to Azure DevOps, so updating the pipeline status badges accordingly.
=> Updated pipeline badges.

azure-pipelines.yml
Using non-RC version of dotnet for build.  Code signing step has been falling since Dec.
=> Using non-RC version of dotnet for build

common.props, src/Microsoft.NET.Sdk.Functions.Generator/MethodInfoExtensions.cs, test/Microsoft.NET.Sdk.Functions.Generator.Tests/FunctionJsonConverterTests.cs
Currently, when a function invocation happens, we [log binding usage](https://github.com/Azure/azure-functions-host/blob/2b9f7dc08ecb0f525f2e55f44d43eedd25a7c0e2/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs#L82) to our function metrics logs table.  We recently found out that not all the bindings were logged for in-proc precompiled apps.
For in-proc apps, the function.json generated is not including all the bindings. It is including only the trigger bindings. In this PR, we are making a change to include all bindings. 
We have also decided to remove the binding direction from the event name when logging the binding metric in host.
=> Include all bindings when generating function metadata

azure-pipelines.yml
V3 builds are failing because 'Microsoft.NETCore.App', version '2.0.0' was not found. This framework version reached end of life, hence dev ops may have removed it from the agents. Because of this, "BuildAndPublish_V1Functions" is failing. Until we figure out what to do with this test, we have decided to explicitly install 2.2.x version to unblock us from merging some other changes waiting to be merged to 3.x
=> Install dotnet 2.2 for v3 builds

src/Microsoft.NET.Sdk.Functions.Generator/MethodInfoExtensions.cs, test/Microsoft.NET.Sdk.Functions.Generator.Tests/FunctionJsonConverterTests.cs
Cherry picking changes from [PR 542](https://github.com/Azure/azure-functions-vs-build-sdk/pull/542) to v3 branch.
----
Currently, when a function invocation happens, we [log binding usage](https://github.com/Azure/azure-functions-host/blob/2b9f7dc08ecb0f525f2e55f44d43eedd25a7c0e2/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs#L82) to our function metrics logs table.  We recently found out that not all the bindings were logged for in-proc precompiled apps.
For in-proc apps, the function.json generated is not including all the bindings. It is including only the trigger bindings. In this PR, we are making a change to include all bindings. 
We have also decided to remove the binding direction from the event name when logging the binding metric in host.
=> [V3 backport] Include all bindings when generating function metadata (#542)

src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.Version.props
Bumping up V3 package version for [Microsoft.NET.Sdk.Functions](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions) . This new version includes the below fix (backported to v3). We have already published the v4 version of this package.
[[V3 backport] Include all bindings when generating function metadata (#542)](https://github.com/Azure/azure-functions-vs-build-sdk/pull/547)
=> Bumping up version of v3 package (3.0.13 to 3.1.0)

common.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.targets
In-proc version of the same change : https://github.com/Azure/azure-functions-dotnet-worker/pull/860
This change helps import the Visual Studio design time targets to the Azure Functions SDK. This helps enable functionality like - File Nesting, Debug property page options, other project system settings etc.
/cc @BillHiebert
=> Import the Functions design time targets

azure-pipelines.yml
Currently the [codesigning task is failing](https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=160325&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=094908eb-9b91-5864-e5bc-10e3f5697105) as it requires 'Microsoft.NETCore.App', version '2.1.0 framework and looks like the agents does not have that anymore.  To fix this we are  switching from EsrpCodeSigning@1 to EsrpCodeSigning@2 which apparently relies on a newer version of the framework which exists in these agents.
Sample run using this PR branch - Code signing step does not fail- https://azfunc.visualstudio.com/Azure%20Functions/_build/results?buildId=160326&view=results
=> [Build]Switching from EsrpCodeSigning@1 to EsrpCodeSigning@2

common.props, src/Microsoft.NET.Sdk.Functions.Generator/Microsoft.NET.Sdk.Functions.Generator.csproj, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.targets, src/Microsoft.NET.Sdk.Functions/Microsoft.NET.Sdk.Functions.csproj
Updates to support .NET 8 builds in the future, in alignment with upcoming tooling feed changes.
This takes inspiration from what's done in the isolated worker mode. However, note that the conditions here are just based on TFM. This will override AzureFunctionsVersion, which should be perfectly fine here.
=> Enabling multiple TFMs / tooling suffixes

eng/ci/code-mirror.yml, nuget.config
- Removed myget reference from nuget config as that is not allowed as per policy
- Added `<clear />` element in nuget config
- Updating code-mirror file to remove v4.x branch as that should not be mirrored.
=> Remove myget reference from nuget config

common.props, src/Microsoft.NET.Sdk.Functions.Generator/AttributeExtensions.cs, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/FunctionsV4SdkTests.cs, test/Microsoft.NET.Sdk.Functions.EndToEnd.Tests/Resources/v4/FunctionAppWithHttpTrigger/HttpFunction.cs
Fixes #641 
- Adding null check to the result of `attribute.AttributeType?.Resolve()` in `IsWebJobsAttribute` method, before calling other methods on the result of that.
- Bumped patch version (new version is 4.4.1)
--------------------------------------------------------------------------
I also investigated the reason why the `Resolve` method was returning null when using nullable parameter.
The problem arises when the function parameter is nullable (e.g., `string? id`) in an in-process .NET 8.0 application. In such cases, the `IsWebJobsAttribute` method is called for `System.Runtime.CompilerServices.NullableAttribute`, and the `attribute.AttributeType.Resolve()` expression returns null, leading to a NullReferenceException.
This code is executed from …
=> 4.4.1 - Fixing NRE in IsWebJobsAttribute

common.props, src/Microsoft.NET.Sdk.Functions.MSBuild/Targets/Microsoft.NET.Sdk.Functions.targets
=> Update SDK to redirect .NET 6 apps to use the custom host (V0)

FunctionsSdkE2ETests/SdkVersion.props
Fix failing test/build [here](https://azfunc.visualstudio.com/public/_build/results?buildId=186980&view=logs&j=64340cd7-31c9-5f4e-1c09-a537a0d43227&t=ce0303b1-1a6e-522e-5e2b-432947ea7ded), use latest version [here](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator/).
=> Fix Reference to ExtensionsMetadataGenerator

README.md
Applying the same fix that was made in https://github.com/Azure/azure-functions-host/pull/11211.
I see now that there are 11 other instances of this across Functions repos. See Azure query: https://github.com/search?q=org%3AAzure%20master%2Fsrc%2FAzure.Functions.Cli%2Fnpm%2Fassets%2Fazure-functions-logo-color-raster.png&type=code. I've created work item https://github.com/Azure/azure-functions-core-tools/issues/4624 to track fixing these.
=> Fixing README logo link
